apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-tester
  labels:
    app: load-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-tester
  template:
    metadata:
      labels:
        app: load-tester
    spec:
      containers:
        - name: ab
          image: jordi/ab # Lightweight Apache Benchmark image
          command: ["tail", "-f", "/dev/null"]
